In [2]:
# Importing the vector library
import numpy as np

# Creating a vector using the numpy library
my_vector = np.array([1, 2, 3, 4, 5])

# Printing the vector
print(my_vector)

[1 2 3 4 5]


In [ ]:
#ADDITION IN VECTORS

In [3]:
A = [1, 2, 3]
B = [4, 5, 6]

C = []
for i in range(len(A)):
    C.append(A[i] + B[i])

print(C)  # Output: [5, 7, 9]

[5, 7, 9]


In [4]:
#SUBTRACTION IN VECTORS
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Subtract the vectors
result = vector2 - vector1

print(result)

[3 3 3]


In [13]:
#SCALAR VECTORS
#Addition in scalar vector
vector1=np.array(3)*[1,2,3]
vector2=np.array(3)*[4,5,6]
print(vector1,vector2)
print(vector1 + vector2)

[3 6 9] [12 15 18]
[15 21 27]


In [10]:
#COMBINATION

import itertools

# Generate combinations of 2 items from a list
items = [1, 2, 3, 4]
combinations = list(itertools.combinations(items, 2))

print(combinations)


[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


In [ ]:
#Transformimg Vectors
import numpy as np

# Define the vector
vector = np.array([1, 2, 3])

# Define the transformation matrix
transformation_matrix = np.array([[2, 0, 0],
                                  [0, 3, 0],
                                  [0, 0, 4]])

# Apply the transformation
transformed_vector = np.dot(transformation_matrix, vector)

# Print the transformed vector
print(transformed_vector)

In [ ]:
#transforming vectors
import numpy as np

# define the vector
vector = np.array([1, 2, 3])

# define the transformation matrix
transformation_matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 2]])

# transform the vector using dot product
transformed_vector = np.dot(transformation_matrix, vector)

print("Original vector:", vector)
print("Transformed vector:", transformed_vector)

In [14]:
#Transforming Matrix

import numpy as np

# Create a 2D matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose the matrix
transposed_matrix = np.transpose(matrix)

# Print the original and transposed matrix
print("Original Matrix:")
print(matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
# more of tranforming matrix

#To transform a matrix in Python, you can use the NumPy library. Here are two examples of common matrix transformations:

#Transpose:

#The transpose of a matrix involves flipping its rows and columns.
#Example:
import numpy as np

matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
transposed_matrix = np.transpose(matrix)

print(transposed_matrix)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
# example 3
import numpy as np

matrix = np.array([[1, 2],
                    [3, 4]])

inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [2]:
#linear Equation

def solve_linear_equation(a, b):
    """
    Solve a linear equation of the form 'ax + b = 0'.

    Parameters:
    a (float): The coefficient of x.
    b (float): The constant term.

    Returns:
    float: The solution to the linear equation.
    """

    if a == 0:
        if b == 0:
            return "Infinite solutions"
        else:
            return "No solution"
    else:
        return -b / a

# Example usage
solution = solve_linear_equation(2, 4)
print(solution)

-2.0


In [19]:
# Example 2
# Equation: y = 2x + 1

x = 5
y = 2*x + 1

print(y) 

11


In [20]:
# Example 3
# Equation: y = 3x - 4

x = 2
y = 3*x - 4

print(y) 

2


In [13]:
# inverse matrix
# # Replace a, b, c, d with the elements of your mat



import numpy as np

matrix = np.array([[2, 3], [1, 4]])
inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)

[[ 0.8 -0.6]
 [-0.2  0.4]]


In [22]:
# Example 2
import numpy as np

# Create a 2x2 matrix
matrix = np.array([[2, 3], [1, 4]])

# Calculate the inverse matrix
inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)

[[ 0.8 -0.6]
 [-0.2  0.4]]


In [14]:
# dot matrix
import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(array1, array2)

# Print the result
print("Dot product:", dot_product)

Dot product: 32


In [16]:
#Example 2
vector3 = np.array([0.5, 1.5])
vector4 = np.array([2, 3])

dot_product = np.dot(vector3, vector4)
print(dot_product)

5.5


In [15]:
#Matrix decomposition
import numpy as np

# Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform matrix decomposition
U, s, V = np.linalg.svd(A)

# Print the decomposed matrices
print("U:\n", U)
print("Singular values:", s)
print("V:\n", V)

U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values: [1.68481034e+01 1.06836951e+00 1.47280825e-16]
V:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]


In [18]:
# Example 2
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
